### ISSUE TITLE
Tests!

### ISSUE THREAD

**Issue by nifty** [michaelenger/sanntid#4]
We should have tests! Like all the other cool guys.

![](http://www.troll.me/images/arnold-angry/no-unit-tests-hasta-la-vista-baby.jpg)

**Comment by michaelenger** [comment]
I am all for writing tests, but I made this thing last evening while sitting at Mathias' watching him play Destiny.

CUT ME SOME SLACK, DAMNIT!
![](http://i.imgur.com/rN0hXSJ.gif)

**Comment by nifty** [comment]
Team work! We'll make this happen together! :star2:

Testing seems to be built into the `go` command, and seems pretty straight forward. There is some information about it here: https://golang.org/doc/code.html#Testing

**Comment by michaelenger** [comment]
I followed [this tutorial](http://golang.org/doc/code.html) which included writing a test. Need to know how to mock the HTTP request, though...

**Comment by nifty** [comment]
Looks like the `http` package comes with a test package as well. Look at: http://golang.org/pkg/net/http/httptest/

I guess maybe the code needs to be restructured slightly to make it more testable? `requestArrivalData` both fetches data and transforms JSON into structs. This should be split into at least two separate functions I guess?

**Comment by michaelenger** [comment]
Yeah, we should do that.

**Comment by michaelenger** [comment]
This is being handled in #7.
