### ISSUE TITLE
Search for stops

### ISSUE THREAD

**Issue by torjusb** [michaelenger/sanntid#6]
Having to pass the locationID for the stop is not useful. We should have a method for searching all the stops.

There isn't any API for searching stops, only a downloadable CSV file which contains all the stops. I suppose the best option is to simply bundle this file with the program? Put it in a `./data` directory or similar.

**Comment by michaelenger** [comment]
Do we want to make any modifications to this CSV? Convert it into a JSON-document? Compile it into the app somehow?

I think that the easiest would be to include the CSV as-is and blame Ruter if it's shit.

PS: Care to link to the CSV file here, btw?

**Comment by nifty** [comment]
The CSV can be found here: http://193.69.180.119:8080/tabledump/stops2.csv
It's in the format of `StopID;Name;Shortname;Municipality;Zone;X;Y;RealTimeDatabaseID`.

I think we should just keep the CSV as it is, and just use the built in [CSV Reader](http://golang.org/pkg/encoding/csv/#Reader) to parse it. It will also reduce the file size, as JSON is generally much larger than CSV-files.

I started playing around with the CSV reader, but didn't get so far. The API isn't as nice as the JSON parser. I'll post the code once I get home.

**Comment by michaelenger** [comment]
Closing this as you can now use a string to select stop instead of having to use the ID.
